version: '3.8'

services:
  minecraft-dashboard:
    image: ghcr.io/niark2/minecraft-dashboard:latest
    container_name: minecraft-dashboard
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Add other volumes if you need persistence for local db files etc.
      # - ${APP_DATA_DIR}/data:/app/data 
    networks:
      - tipi_main_network

networks:
  tipi_main_network:
    external: true
